version: '3.8'

# plantilla base (no es un servicio activo)
x-base-config: &base-config
  image: chatwoot/chatwoot:latest
  env_file: .env
  volumes:
    - storage_data:/app/storage

services:
  rails:
    <<: *base-config
    depends_on:
      - postgres
      - redis
    ports:
      - '4000:3000'
    environment:
      - NODE_ENV=production
      - RAILS_ENV=production
      - INSTALLATION_ENV=docker
      - REDIS_URL=${REDIS_URL}
    entrypoint: docker/entrypoints/rails.sh
    command: ['bundle','exec','rails','s','-p','3000','-b','0.0.0.0']
    restart: always

  sidekiq:
    <<: *base-config
    depends_on:
      - postgres
      - redis
    environment:
      - NODE_ENV=production
      - RAILS_ENV=production
      - INSTALLATION_ENV=docker
      - REDIS_URL=${REDIS_URL}
      - DATABASE_URL=${DATABASE_URL}
    command: ['bundle','exec','sidekiq','-C','config/sidekiq.yml']
    restart: always

  postgres:
    image: pgvector/pgvector:pg16
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DATABASE}
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  redis:
    image: redis:alpine
    restart: always
    # Opción A: sin contraseña
    command: ["redis-server"]
    # Opción B: con contraseña
    # command: ["sh","-c","redis-server --requirepass \"$REDIS_PASSWORD\""]
    env_file: .env
    volumes:
      - redis_data:/data
    ports:
      - '6379:6379'

volumes:
  storage_data:
  postgres_data:
  redis_data:
